[pytest]
addopts = -s -v

markers =
    smoke: Маркер для дымовых тестов.
    selenium: Маркер тестов на Selenium.
    playwright: Маркер тестов на Playwright.
    ui: Маркер для ui-тестов.
    api: Маркер для api-тестов.